# Generated by Django 3.1.7 on 2021-02-21 22:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_leaveapplication_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('leave_status', models.CharField(choices=[('Approved', 'Approved'), ('Denied', 'Denied')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reason', to=settings.AUTH_USER_MODEL),
        ),
    ]
